### PR TITLE
Update a few spots in readme and fix a require statement

### PR DESCRIPTION
**Pull request by DaveWelling**
I really appreciated the work you did in this repo, so I wanted to suggest a few fixes so I could share it with others that are using android.  Hope this helps.

### CODE REVIEW

**Comment by kkbhav** [comment]
@DaveWelling, the repo react-native-fetch-blob is updated and now uses rn-fetch-blob as the project name internally. Which is why there is a discrepancy in the names.

Also, I have made some changes in fetch-blob library to bypass some errors in case of file-uri detection. I did not have time to put the PR back to the library. Please go through the mentioned install process and let me know if you encounter any problems in that.

**Comment by kkbhav** [comment]
@DaveWelling, I found out that I did not update the installation instructions after updating my react-native-fetch-blob repo. Please try it once again.

Sorry for the inconvenience caused.

**Comment by DaveWelling** [comment]
@kkbhav Thanks for taking a look at the PR, thanks for the commit and thanks for creating these libraries!  I am very happy to have found your repos.  I will test out the new commit, but I haven't gotten to it yet.  Assuming everything works, the PR change I made to the README.md link and RNPatchUtil.js will not be necessary, right?  I think the Android specific changes I made to the README.md might still be necessary?  Would you like me to change this PR with just those changes?  
I was also trying to think of a way to help you create an NPM package with SEMVER to avoid similar problems in the future, but I think it just needs an `NPM publish <package-name>` for both?
I know it is a pain to work with two packages simultaneously, updating both, have you considered using the `npm link` command to help with that instead of directly linking the git repositories?  Let me know if there is anything I can do to help, and thanks again!

**Comment by kkbhav** [comment]
@DaveWelling I finally got the time to push npm package. Please have a look.
[pouchdb-adapters-rn](https://www.npmjs.com/package/pouchdb-adapters-rn)

Also, fetch-blob is used internally by this library and the official library have not merged my [PR](https://github.com/joltup/rn-fetch-blob/pull/165) till now. I need this PR to get merged so that I can use the npm version of this library. Till that time, we have to custom install the fetch-blob package.

**Pull request closed without merging**
